package com.jonatas.blog.config;

import java.time.LocalDateTime;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.jonatas.blog.model.PostModel;
import com.jonatas.blog.repository.PostRepository;

@Configuration
@Profile(value = "test")
public class PostConfig implements CommandLineRunner {

    @Autowired
    private PostRepository postRepository;

    PostModel post1 = new PostModel("Como usar o Thymelead", "Jonatas Caetano", LocalDateTime.now(),
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu euismod nunc. Pellentesque malesuada semper felis, eget euismod turpis vehicula at. Aliquam erat volutpat. Duis ligula dui, euismod quis massa at, volutpat tincidunt arcu. Cras tempor massa id eros fringilla, a suscipit dolor laoreet. Donec rhoncus mattis tellus. Sed consectetur felis vel sollicitudin scelerisque. Duis tincidunt et dui sit amet rutrum. Donec bibendum lacinia purus vestibulum facilisis. Mauris lobortis ante sem, non sollicitudin ex mollis eu."
                    + "Curabitur porttitor aliquet faucibus. Praesent eu sapien diam. Vestibulum id congue lectus, a sollicitudin dui. Phasellus id tortor rutrum ligula placerat consequat at non dui. Nam dignissim nulla ac lacinia tempus. Nullam vel ipsum ornare, vestibulum mi vel, suscipit mi. Vestibulum ut volutpat nunc. Mauris quis magna purus. Vivamus at dignissim dolor, congue varius nibh. Ut malesuada bibendum aliquam."
                    + "Nulla eu risus erat. Morbi eu purus vitae dui tincidunt volutpat quis eu enim. Nulla sodales augue vitae risus vulputate euismod vel eu ante. Donec fermentum sed erat eu efficitur. Nullam iaculis ut neque nec vehicula. Aliquam ornare purus eget egestas tristique. Aliquam fermentum volutpat metus. Proin rutrum venenatis leo, non rhoncus velit ornare at. Vivamus ac congue velit. Ut scelerisque augue ut tincidunt porta. Etiam pulvinar rutrum felis vel eleifend. Proin id maximus mi, mattis dignissim dolor. Ut id pellentesque metus. Aliquam nec elit sit amet purus volutpat efficitur."
                    + "Pellentesque dignissim est interdum orci rhoncus, non efficitur est porttitor. Suspendisse vel pretium ante. Donec tempor eros a pharetra tempor. Sed eu tincidunt turpis. Cras in pharetra quam. Donec vitae mauris quis libero interdum varius vitae quis velit. Fusce et convallis neque. Etiam sed eleifend felis, non congue sapien."
                    + "Donec eleifend sem non neque rutrum, luctus auctor purus viverra. Morbi dignissim orci id sem tempor, id pretium tortor eleifend. Morbi sodales mi quis urna ornare, ac facilisis erat placerat. Fusce condimentum ligula nec eros placerat euismod. Aliquam id magna nec dui molestie fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam lectus orci, facilisis sit amet orci ac, laoreet aliquam nunc. Donec at elit ultrices, aliquam diam vel, rhoncus velit. Morbi suscipit id libero a tincidunt. Vestibulum gravida dui eu nibh gravida, vitae auctor nunc pretium. Cras consequat accumsan varius. Nam sed tortor vel ante suscipit tincidunt ac eu est. Aliquam hendrerit magna vestibulum, dignissim risus a, tincidunt arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

    PostModel post2 = new PostModel("Crie um crud com mongodb", "Jonatas Caetano", LocalDateTime.now(),
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu euismod nunc. Pellentesque malesuada semper felis, eget euismod turpis vehicula at. Aliquam erat volutpat. Duis ligula dui, euismod quis massa at, volutpat tincidunt arcu. Cras tempor massa id eros fringilla, a suscipit dolor laoreet. Donec rhoncus mattis tellus. Sed consectetur felis vel sollicitudin scelerisque. Duis tincidunt et dui sit amet rutrum. Donec bibendum lacinia purus vestibulum facilisis. Mauris lobortis ante sem, non sollicitudin ex mollis eu."
                    + "Curabitur porttitor aliquet faucibus. Praesent eu sapien diam. Vestibulum id congue lectus, a sollicitudin dui. Phasellus id tortor rutrum ligula placerat consequat at non dui. Nam dignissim nulla ac lacinia tempus. Nullam vel ipsum ornare, vestibulum mi vel, suscipit mi. Vestibulum ut volutpat nunc. Mauris quis magna purus. Vivamus at dignissim dolor, congue varius nibh. Ut malesuada bibendum aliquam."
                    + "Nulla eu risus erat. Morbi eu purus vitae dui tincidunt volutpat quis eu enim. Nulla sodales augue vitae risus vulputate euismod vel eu ante. Donec fermentum sed erat eu efficitur. Nullam iaculis ut neque nec vehicula. Aliquam ornare purus eget egestas tristique. Aliquam fermentum volutpat metus. Proin rutrum venenatis leo, non rhoncus velit ornare at. Vivamus ac congue velit. Ut scelerisque augue ut tincidunt porta. Etiam pulvinar rutrum felis vel eleifend. Proin id maximus mi, mattis dignissim dolor. Ut id pellentesque metus. Aliquam nec elit sit amet purus volutpat efficitur."
                    + "Pellentesque dignissim est interdum orci rhoncus, non efficitur est porttitor. Suspendisse vel pretium ante. Donec tempor eros a pharetra tempor. Sed eu tincidunt turpis. Cras in pharetra quam. Donec vitae mauris quis libero interdum varius vitae quis velit. Fusce et convallis neque. Etiam sed eleifend felis, non congue sapien."
                    + "Donec eleifend sem non neque rutrum, luctus auctor purus viverra. Morbi dignissim orci id sem tempor, id pretium tortor eleifend. Morbi sodales mi quis urna ornare, ac facilisis erat placerat. Fusce condimentum ligula nec eros placerat euismod. Aliquam id magna nec dui molestie fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam lectus orci, facilisis sit amet orci ac, laoreet aliquam nunc. Donec at elit ultrices, aliquam diam vel, rhoncus velit. Morbi suscipit id libero a tincidunt. Vestibulum gravida dui eu nibh gravida, vitae auctor nunc pretium. Cras consequat accumsan varius. Nam sed tortor vel ante suscipit tincidunt ac eu est. Aliquam hendrerit magna vestibulum, dignissim risus a, tincidunt arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

    PostModel post3 = new PostModel("Porque estudar Java em 2023?", "Jonatas Caetano", LocalDateTime.now(),
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu euismod nunc. Pellentesque malesuada semper felis, eget euismod turpis vehicula at. Aliquam erat volutpat. Duis ligula dui, euismod quis massa at, volutpat tincidunt arcu. Cras tempor massa id eros fringilla, a suscipit dolor laoreet. Donec rhoncus mattis tellus. Sed consectetur felis vel sollicitudin scelerisque. Duis tincidunt et dui sit amet rutrum. Donec bibendum lacinia purus vestibulum facilisis. Mauris lobortis ante sem, non sollicitudin ex mollis eu."
                    + "Curabitur porttitor aliquet faucibus. Praesent eu sapien diam. Vestibulum id congue lectus, a sollicitudin dui. Phasellus id tortor rutrum ligula placerat consequat at non dui. Nam dignissim nulla ac lacinia tempus. Nullam vel ipsum ornare, vestibulum mi vel, suscipit mi. Vestibulum ut volutpat nunc. Mauris quis magna purus. Vivamus at dignissim dolor, congue varius nibh. Ut malesuada bibendum aliquam."
                    + "Nulla eu risus erat. Morbi eu purus vitae dui tincidunt volutpat quis eu enim. Nulla sodales augue vitae risus vulputate euismod vel eu ante. Donec fermentum sed erat eu efficitur. Nullam iaculis ut neque nec vehicula. Aliquam ornare purus eget egestas tristique. Aliquam fermentum volutpat metus. Proin rutrum venenatis leo, non rhoncus velit ornare at. Vivamus ac congue velit. Ut scelerisque augue ut tincidunt porta. Etiam pulvinar rutrum felis vel eleifend. Proin id maximus mi, mattis dignissim dolor. Ut id pellentesque metus. Aliquam nec elit sit amet purus volutpat efficitur."
                    + "Pellentesque dignissim est interdum orci rhoncus, non efficitur est porttitor. Suspendisse vel pretium ante. Donec tempor eros a pharetra tempor. Sed eu tincidunt turpis. Cras in pharetra quam. Donec vitae mauris quis libero interdum varius vitae quis velit. Fusce et convallis neque. Etiam sed eleifend felis, non congue sapien."
                    + "Donec eleifend sem non neque rutrum, luctus auctor purus viverra. Morbi dignissim orci id sem tempor, id pretium tortor eleifend. Morbi sodales mi quis urna ornare, ac facilisis erat placerat. Fusce condimentum ligula nec eros placerat euismod. Aliquam id magna nec dui molestie fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam lectus orci, facilisis sit amet orci ac, laoreet aliquam nunc. Donec at elit ultrices, aliquam diam vel, rhoncus velit. Morbi suscipit id libero a tincidunt. Vestibulum gravida dui eu nibh gravida, vitae auctor nunc pretium. Cras consequat accumsan varius. Nam sed tortor vel ante suscipit tincidunt ac eu est. Aliquam hendrerit magna vestibulum, dignissim risus a, tincidunt arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

    PostModel post4 = new PostModel("React.js vs Angular qual o melhor framework javascript? ", "Jonatas Caetano",
            LocalDateTime.now(),
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu euismod nunc. Pellentesque malesuada semper felis, eget euismod turpis vehicula at. Aliquam erat volutpat. Duis ligula dui, euismod quis massa at, volutpat tincidunt arcu. Cras tempor massa id eros fringilla, a suscipit dolor laoreet. Donec rhoncus mattis tellus. Sed consectetur felis vel sollicitudin scelerisque. Duis tincidunt et dui sit amet rutrum. Donec bibendum lacinia purus vestibulum facilisis. Mauris lobortis ante sem, non sollicitudin ex mollis eu."
                    + "Curabitur porttitor aliquet faucibus. Praesent eu sapien diam. Vestibulum id congue lectus, a sollicitudin dui. Phasellus id tortor rutrum ligula placerat consequat at non dui. Nam dignissim nulla ac lacinia tempus. Nullam vel ipsum ornare, vestibulum mi vel, suscipit mi. Vestibulum ut volutpat nunc. Mauris quis magna purus. Vivamus at dignissim dolor, congue varius nibh. Ut malesuada bibendum aliquam."
                    + "Nulla eu risus erat. Morbi eu purus vitae dui tincidunt volutpat quis eu enim. Nulla sodales augue vitae risus vulputate euismod vel eu ante. Donec fermentum sed erat eu efficitur. Nullam iaculis ut neque nec vehicula. Aliquam ornare purus eget egestas tristique. Aliquam fermentum volutpat metus. Proin rutrum venenatis leo, non rhoncus velit ornare at. Vivamus ac congue velit. Ut scelerisque augue ut tincidunt porta. Etiam pulvinar rutrum felis vel eleifend. Proin id maximus mi, mattis dignissim dolor. Ut id pellentesque metus. Aliquam nec elit sit amet purus volutpat efficitur."
                    + "Pellentesque dignissim est interdum orci rhoncus, non efficitur est porttitor. Suspendisse vel pretium ante. Donec tempor eros a pharetra tempor. Sed eu tincidunt turpis. Cras in pharetra quam. Donec vitae mauris quis libero interdum varius vitae quis velit. Fusce et convallis neque. Etiam sed eleifend felis, non congue sapien."
                    + "Donec eleifend sem non neque rutrum, luctus auctor purus viverra. Morbi dignissim orci id sem tempor, id pretium tortor eleifend. Morbi sodales mi quis urna ornare, ac facilisis erat placerat. Fusce condimentum ligula nec eros placerat euismod. Aliquam id magna nec dui molestie fringilla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam lectus orci, facilisis sit amet orci ac, laoreet aliquam nunc. Donec at elit ultrices, aliquam diam vel, rhoncus velit. Morbi suscipit id libero a tincidunt. Vestibulum gravida dui eu nibh gravida, vitae auctor nunc pretium. Cras consequat accumsan varius. Nam sed tortor vel ante suscipit tincidunt ac eu est. Aliquam hendrerit magna vestibulum, dignissim risus a, tincidunt arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

    @Override
    public void run(String... args) throws Exception {
        postRepository.saveAll(Arrays.asList(post1, post2, post3, post4));
        postRepository.findAll().stream().forEach(x -> System.out.println(x.toString()));

    }

}
